### ISSUE TITLE
Qustions about the saved files

### ISSUE THREAD

**Issue by YouthBL** [Sofianebouaziz1/FLASH-RL#1]
Thank you for your open source spirit, it is great work and has given me a lot of help in learning.  Recently, I have successfully run the code following the tutorial. But I encountered a problem. The question is about the .pkl files in clients_info. If I want to change to the MNIST or other datasets, how should these corresponding .pkl files be generated?

**Comment by Sofianebouaziz1** [comment]
Thank you for reaching out! 

Regarding your question about switching datasets, particularly for the MNIST dataset, the .pkl files in the 'clients_info' directory are structured similarly to those for the CIFAR-10 dataset, due to the fixed number of clients, _N = 100_ (with the only difference being the number of samples).

To diversify the client pool, we've categorized them into four groups based on their performance capabilities and edge equipment:

1. High-Performance Clients with High-Performance Edge Equipment and Efficient Transfer Protocols.
2. Moderate-Performance Clients with High-Performance Edge Equipment and Inefficient Transfer Protocols.
3. Moderate-Performance Clients with Limited Edge Equipment and High-Performance Transfer Protocols.
4. Low-Performance Clients with Limited Edge Equipment and Inefficient Transfer Protocols.

For integrating other datasets, similar .pkl files should be manually generated using the same hierarchical classification approach mentioned above.

I hope this clarifies the process. Feel free to reach out if you have any further questions.

**Comment by YouthBL** [comment]
I got that, thank you very much for your reply. I'll try it soon.
